#pragma once
#include "raylib.h"
#include <string>
#include <fstream>
#include <sstream>
#include <iostream>
#include <filesystem>
#include "chrono"
#include <ctime>
#include <vector>
#include <iomanip>
#include "raymath.h"
#include <algorithm>
#include <cmath>